# This migration yaml assumes that the Confluent Operator 1.x deployment is in `confluent` namespace.
# Change this to your namespace.
apiVersion: platform.confluent.io/v1beta1
kind: MigrationJob
metadata:
  name: migration
  namespace: confluent
spec:
  # Specify the init container image and version tag that corresponds to your Confluent Platform
  # version. In this example, Confluent Platform 6.0.2 is being used. 
  initContainerImage: confluentinc/cp-init-container-operator:v6.0.2.0
  zookeeper:
    enabled: false
    name: zookeeper
    namespace: confluent
    release: zookeeper
  kafka:
    enabled: false
    name: kafka
    namespace: confluent
    release: kafka
    zookeeperEndpoint: zookeeper.confluent.svc.cluster.local:2181
  controlcenter:
    enabled: false
    name: controlcenter
    namespace: confluent
    release: controlcenter
  connect:
    enabled: false
    name: connectors
    namespace: confluent
    release: connect
  ksqldb:
    enabled: false
    name: ksql
    namespace: confluent
    release: ksql
  replicator:
    enabled: false
    name: replicator
    namespace: confluent
    release: replicator
  schemaRegistry:
    enabled: false
    name: schemaregistry
    namespace: confluent
    release: schemaregistry
