apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: source-kraft
  namespace: confluent
spec:
  dataVolumeCapacity: 10G
  image:
    application: docker.io/confluentinc/cp-server:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  replicas: 3
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: source-kafka
  namespace: confluent
spec:
  dataVolumeCapacity: 10G
  image:
    application: docker.io/confluentinc/cp-server:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  replicas: 3
  dependencies:
    kRaftController:
      clusterRef:
        name: source-kraft
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: krc-source
  namespace: confluent
spec:
  kafkaClusterRef:
    name: source-kafka
  kafkaRest:
    endpoint: http://source-kafka.confluent.svc.cluster.local:8090
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demotopic
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: krc-source
  replicas: 3
  partitionCount: 4
  configs:
    cleanup.policy: "delete"
