apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: sampletopic
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: krc-destination
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"
